version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3307:3307'

    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=bookingapp
    volumes:
      - ./mysql:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3307
      - MYSQL_USERNAME=root
      - MYSQL_NAME=bookingapp

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
